#!/usr/bin/env bash
set -euo pipefail

input=$(cat)
if [ -z "$input" ]; then
  exit 0
fi

file_path=$(echo "$input" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('tool_input', {}).get('file_path', ''))
except Exception:
    print('')
" 2>/dev/null || echo "")

if [ -z "$file_path" ]; then
  exit 0
fi

# Block writes to auto-generated TypeScript types
# These files are regenerated by 'task dev:generate' — manual edits are overwritten
if echo "$file_path" | grep -qE "frontend/app/lib/api/types/.*\.ts$"; then
  echo "ERROR: $file_path is auto-generated from Pydantic models." >&2
  echo "To fix a type: change the Python schema in mealie/schema/, then run 'task dev:generate'." >&2
  echo "For custom types that cannot be generated, use frontend/app/lib/api/types/non-generated.ts" >&2
  exit 2
fi

# Block writes that would CREATE a new migration in the versions directory
# (creating new migrations is OK, but only via 'task py:migrate' — not by hand)
# We only block if this looks like a hand-crafted migration file (not autogenerated)
# Actually, we allow new file creation — only block editing existing ones (handled in Edit hook)

# Warn about .env files that may contain secrets
if echo "$file_path" | grep -qE "^\.(env|dev\.env)$|^\.env\..+$"; then
  echo "WARNING: Writing to $file_path which may contain secrets." >&2
  echo "Ensure this file is in .gitignore and secrets are never committed." >&2
  # Don't block — just warn
fi

exit 0
